import { ReportMetrics } from './metrics.js';

function formatPerson(login: string, displayNameByLogin: Record<string, string>) {
  const display = displayNameByLogin[login];
  if (display && display.trim() && display !== login) return `${display} (${login})`;
  return login;
}

export function renderMarkdown(
  client: string,
  org: string,
  metrics: ReportMetrics,
  displayNameByLogin: Record<string, string> = {},
) {
  const lines: string[] = [];
  const title =
    metrics.window.period === 'weekly'
      ? 'Weekly'
      : metrics.window.period === 'monthly'
        ? 'Monthly'
        : 'Quarterly';
  lines.push(`# ${title} engineering metrics (${client})`);
  lines.push('');
  lines.push(`Org: **${org}**`);
  if (metrics.window.label) {
    lines.push(`Period: **${metrics.window.label}**`);
  }
  const windowLabel =
    metrics.window.period === 'weekly' ? `last ${metrics.window.days} days` : `${metrics.window.days} days`;
  lines.push(`Window: **${metrics.window.start} → ${metrics.window.end}** (${windowLabel})`);
  lines.push('');

  lines.push('## Totals');
  lines.push('');
  lines.push(`- PRs opened: **${metrics.totals.prsOpened}**`);
  lines.push(`- PRs merged: **${metrics.totals.prsMerged}**`);
  lines.push(`- PRs closed (unmerged): **${metrics.totals.prsClosedUnmerged}**`);
  lines.push('');

  lines.push('## By engineer');
  lines.push('');

  const authors = Object.entries(metrics.byAuthor).sort((a, b) => b[1].prsMerged - a[1].prsMerged);
  for (const [author, m] of authors) {
    lines.push(`### ${formatPerson(author, displayNameByLogin)}`);
    lines.push('');
    lines.push(`- PRs opened: **${m.prsOpened}**`);
    lines.push(`- PRs merged: **${m.prsMerged}**`);
    lines.push(`- PRs closed (unmerged): **${m.prsClosedUnmerged}**`);
    if (m.medianCycleTimeHours != null) lines.push(`- Median cycle time (hrs): **${m.medianCycleTimeHours.toFixed(1)}**`);
    if (m.medianTimeToFirstReviewHours != null) lines.push(`- Median time to first review (hrs): **${m.medianTimeToFirstReviewHours.toFixed(1)}**`);
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by eng-metrics.');

  return lines.join('\n');
}
